-   id: commitcanvas
    name: commitcanvas
    entry: check
    verbose: False
    language: python
    pass_filenames: false
    args: ["--commit",".git/COMMIT_EDITMSG"]
    stages: [prepare-commit-msg]
    
