-   id: commitcanvas
    name: commitcanvas
    entry: check
    verbose: False
    language: python
    pass_filenames: false
    stages: [prepare-commit-msg]
    args: ['--path', 'description', '--msg_file', '.git/COMMIT_EDITMSG']
    
