[tool.poetry]
name = "CommitCanvas"
version = "0.1.0"
description = ""
authors = ["bagashvilit <bagashvilit@allegheny.edu>"]

[tool.poetry.dependencies]
python = "^3.7"
pre-commit = "^2.5.1"
spacy = "^2.3.2"
en = "^0.0.1"
en_core_web_sm = { url = "https://github.com/explosion/spacy-models/releases/download/en_core_web_sm-2.3.0/en_core_web_sm-2.3.0.tar.gz" }
pathlib = "^1.0.1"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[tool.poetry.scripts]
commitcanvas = "commitcanvas.__main__:main"

# [tool.poetry.plugins."blogtool.parsers"]
# "commitcanvas" = "commitcanvas.__main__:main"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
