[tool.poetry]
name = "CommitCanvas"
version = "0.1.0"
description = ""
authors = ["bagashvilit <bagashvilit@allegheny.edu>"]

[tool.poetry.dependencies]
python = ">=3.6.1"
pre-commit = "^2.5.1"
spacy = "^2.3.2"
en_core_web_sm = { url = "https://github.com/explosion/spacy-models/releases/download/en_core_web_sm-2.3.1/en_core_web_sm-2.3.1.tar.gz" }


[tool.poetry.dev-dependencies]
pytest = "^5.3.5"
pytest-cov = "^2.10.0"

[tool.poetry.scripts]
commitcanvas = "commitcanvas.__main__:main"

# [tool.poetry.plugins."blogtool.parsers"]
# "commitcanvas" = "commitcanvas.__main__:main"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
