[tool.poetry]
name = "CommitCanvas"
version = "0.1.0"
description = ""
authors = ["bagashvilit <bagashvilit@allegheny.edu>"]

[tool.poetry.dependencies]
python = ">=3.7.1"
pre-commit = "^2.5.1"
spacy = "^2.3.2"
en_core_web_sm = { url = "https://github.com/explosion/spacy-models/releases/download/en_core_web_sm-2.3.1/en_core_web_sm-2.3.1.tar.gz" }
pyarrow = "^3.0.0"
typer = "^0.3.2"
matplotlib = "^3.4.1"
nltk = "^3.6.2"
scikit-learn = "^0.24.2"
PyDriller = "^1.15.5"
pandas = "^1.2.4"

[tool.poetry.dev-dependencies]
pytest = "^5.3.5"
pytest-cov = "^2.10.0"
codecov = "^2.1.8"

[tool.poetry.scripts]
commitcanvas = "commitcanvas.generate_type.classify:entry"
#save = "commitcanvas.generate_type.data_processing:save"

# [tool.poetry.plugins."blogtool.parsers"]
# "commitcanvas" = "commitcanvas.__main__:main"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
