"""Autogenerated file."""
# -*- coding: utf-8 -*-
# DO NOT EDIT THIS FILE!
# This file has been autogenerated by dephell <3
# https://github.com/dephell/dephell

try:
    from setuptools import setup
except ImportError:
    from distutils.core import setup

README = ""

setup(
    long_description=README,
    name="CommitCanvas",
    version="0.1.0",
    description="Empty file required by pylint.",
    python_requires="==3.*,>=3.7.0",
    author="bagashvilit",
    author_email="bagashvilit@allegheny.edu",
    entry_points={
        "blogtool.parsers": ["commitcanvas = commitcanvas.__main__:main"],
        "console_scripts": ["commitcanvas = commitcanvas.__main__:main"],
    },
    packages=["commitcanvas"],
    package_dir={"": "."},
    package_data={},
    install_requires=[
        "en==0.*,>=0.0.1",
        "en-core-web-sm",
        "pre-commit==2.*,>=2.5.1",
        "spacy==2.*,>=2.2.0",
    ],
    extras_require={"dev": ["pytest==5.*,>=5.2.0"]},
)
